name: deno test
on: workflow_call
jobs:
  test-deno:
    timeout-minutes: 10
    runs-on: ubuntu-24.04
    permissions: {}
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - uses: aquaproj/aqua-installer@ea518c135a02fc11ff8024364510c181a5c6b342 # v4.0.3
        with:
          aqua_version: v2.55.1
      - run: deno check
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}
      - run: deno lint
